// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: replication.proto

package replication

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReplicationServiceClient is the client API for ReplicationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplicationServiceClient interface {
	// Fetch returns a stream of log entries from a partition.
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (ReplicationService_FetchClient, error)
	// ReportLEO allows replicas to report their Log End Offset (LEO) to the leader.
	ReportLEO(ctx context.Context, in *ReportLEORequest, opts ...grpc.CallOption) (*ReportLEOResponse, error)
}

type replicationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicationServiceClient(cc grpc.ClientConnInterface) ReplicationServiceClient {
	return &replicationServiceClient{cc}
}

func (c *replicationServiceClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (ReplicationService_FetchClient, error) {
	stream, err := c.cc.NewStream(ctx, &ReplicationService_ServiceDesc.Streams[0], "/replication.ReplicationService/Fetch", opts...)
	if err != nil {
		return nil, err
	}
	x := &replicationServiceFetchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ReplicationService_FetchClient interface {
	Recv() (*FetchResponse, error)
	grpc.ClientStream
}

type replicationServiceFetchClient struct {
	grpc.ClientStream
}

func (x *replicationServiceFetchClient) Recv() (*FetchResponse, error) {
	m := new(FetchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *replicationServiceClient) ReportLEO(ctx context.Context, in *ReportLEORequest, opts ...grpc.CallOption) (*ReportLEOResponse, error) {
	out := new(ReportLEOResponse)
	err := c.cc.Invoke(ctx, "/replication.ReplicationService/ReportLEO", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicationServiceServer is the server API for ReplicationService service.
// All implementations must embed UnimplementedReplicationServiceServer
// for forward compatibility
type ReplicationServiceServer interface {
	// Fetch returns a stream of log entries from a partition.
	Fetch(*FetchRequest, ReplicationService_FetchServer) error
	// ReportLEO allows replicas to report their Log End Offset (LEO) to the leader.
	ReportLEO(context.Context, *ReportLEORequest) (*ReportLEOResponse, error)
	mustEmbedUnimplementedReplicationServiceServer()
}

// UnimplementedReplicationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedReplicationServiceServer struct {
}

func (UnimplementedReplicationServiceServer) Fetch(*FetchRequest, ReplicationService_FetchServer) error {
	return status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedReplicationServiceServer) ReportLEO(context.Context, *ReportLEORequest) (*ReportLEOResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportLEO not implemented")
}
func (UnimplementedReplicationServiceServer) mustEmbedUnimplementedReplicationServiceServer() {}

// UnsafeReplicationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicationServiceServer will
// result in compilation errors.
type UnsafeReplicationServiceServer interface {
	mustEmbedUnimplementedReplicationServiceServer()
}

func RegisterReplicationServiceServer(s grpc.ServiceRegistrar, srv ReplicationServiceServer) {
	s.RegisterService(&ReplicationService_ServiceDesc, srv)
}

func _ReplicationService_Fetch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReplicationServiceServer).Fetch(m, &replicationServiceFetchServer{stream})
}

type ReplicationService_FetchServer interface {
	Send(*FetchResponse) error
	grpc.ServerStream
}

type replicationServiceFetchServer struct {
	grpc.ServerStream
}

func (x *replicationServiceFetchServer) Send(m *FetchResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ReplicationService_ReportLEO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportLEORequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServiceServer).ReportLEO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/replication.ReplicationService/ReportLEO",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServiceServer).ReportLEO(ctx, req.(*ReportLEORequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReplicationService_ServiceDesc is the grpc.ServiceDesc for ReplicationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReplicationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "replication.ReplicationService",
	HandlerType: (*ReplicationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportLEO",
			Handler:    _ReplicationService_ReportLEO_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Fetch",
			Handler:       _ReplicationService_Fetch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "replication.proto",
}
